### ISSUE TITLE
Initial draft of SRS ready for review!

### ISSUE THREAD

**Issue by andreamclemeno** [andreamclemeno/CAS741-Diagnose#2]
Good Evening everyone!

The PDF and LaTex files for my initial draft of my Problem Statement are currently on my project repo: CAS741-Concentration-of-Virus. Please review them! At the end of this issue, you can find the links on the corresponding paths. I added the Comments.tex, .bib file and other images as well in the same folder. Also, my bibliography was working earlier but not anymore. I just relooked at my files. I am going to look into it and I will edit this out once I do. Sorry about that.

Thanks in advance for your feedback!

PDF: [CAS741-Concentration-of-Virus/docs/SRS/741_ViralLoad_docs_SRS_SRS.pdf](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/741_ViralLoad_docs_SRS_SRS.pdf)
LaTex:  [CAS741-Concentration-of-Virus/docs/SRS/741_ViralLoad_docs_SRS_SRS.tex](https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/741_ViralLoad_docs_SRS_SRS.tex)

@smiths 
@liziscool
@machadotiagom

**Comment by machadotiagom** [comment]
Hi @andreamclemeno 

I have read and did the first review on your SRS document. Hope that helps you on the CAS 741 Project.

**Introduction section**
- First line is starting with a (?) symbol. Please, check it out.
- Table 3 containing abbreviations and acronyms appears between the introductory paragraph and Purpose of Document section, which I believe is not correct.

**Organization of document section**
- I think you could be more specific on how instance models can leverage the understanding of the system since sections like that just provide tables on how a theoretical and/or generalized description will be expected to be implemented I guess. I mean, to claim that maybe you should give a better context on how those sections are related to each other.

**System Context section**
- Figure 1 is depicted with low resolution and a bit distorted. We can barely see the arrows in the figure that you point out in your text. I might suggest you to use the following tex command in replacing the one you used in your code:For instance, replace this \includegraphics[width=0.6\textwidth] for this \includegraphics[scale=0.5], where scale = 1.0 means figure size in 100%.
- Is it true that if a user provides data for two consecutive days the software will predict results for 30 days?

**Terminology and Definitions section**
- The following terms have the same definition. Is that true? Sounds weird to me.
                               Decaying: Physical quantity undergoing a constant decline.
                               Clearance: Physical quantity undergoing a constant decline.
- You've mentioned CD4+ cells but I could not find any definition or explanation on what it is.

**Theoretical, General and Instance Models sections**
- If I am not mistaken, all sources must be referenced and added at the end of the SRS document as a bibliography (even if a website or Wikipedia). I suggest you double-check this with Prof Spencer.

**Functional requirements section**
- R1 does not seem a requirement but instead an input. So, should not it be stated differently as "what the software will do" with a proper input?
- R4: there is an issue on the reference of IM. One is appearing like IM??

**Nonfunctional requirements section**
I do not have a background in SW/CS but I am not sure if non-functional requirements are presented the way you presented. For instance, by correctness, what do you mean by stating that "The output values have to adhere to the output properties..."? Does that mean that your program functionally is correct because it behaves according to its stated functional specifications? Hope Prof Spencer will give all of us feedback on this.

Thanks,
Tiago.

**Comment by andreamclemeno** [comment]
@machadotiagom Thanks so much for your feedback! I have been very busy lately but I am going to review these tonight!

Andrea

**Comment by smiths** [comment]
@machadotiagom, in the future please create your issues as issues in GitHub, rather than as comments.  Ideally there should be one concern per GitHub issue.  In this way @andreamclemeno can close each one independently.

@machadotiagom is correct that sources should be referenced.

With respect to the nonfunctional requirement for correctness, it is redundant to say that the outputs will adhere to the output properties.  We already know this because there are functional requirements for this.  :smile:  In some cases there are nonfunctional requirements related to accuracy.  Accuracy says how far off the correct solution the calculated solution is allowed to be.  Unfortunately this is a very difficult nonfunctional requirement to actually achieve with scientific software.

In the current case, it is probably best to remove the correctness requirement.  It is already implied by the other requirements.  We can use the VnV document to explore what we mean by correctness.

**Comment by smiths** [comment]
The SRS is reviewed in the scanned pdf provided in e05cbb3.  Please address the comments.  You should create issues as appropriate.
