### ISSUE TITLE
Drasil generated SRS ready for review!

### ISSUE THREAD

**Issue by andreamclemeno** [andreamclemeno/CAS741-Diagnose#20]
Good evening Dr. Smith!!

The pdf of the .html is found on my project repo: https://github.com/andreamclemeno/CAS741-Concentration-of-Virus/blob/master/docs/SRS/Software%20Requirements%20Specification%20for%20Diagnose%20(1).pdf

The repo that this generated from is: https://github.com/andreamclemeno/Drasil

My code can be found: https://github.com/andreamclemeno/Drasil/tree/master/code/drasil-example/Drasil/Diagnose

Please make issues so I can improve my project!!

Thank you :)

Andrea

@smiths

**Comment by smiths** [comment]
@andreamclemeno, I've provided comments on your Drasil generated SRS in d88268a.

I don't have any comments on the Drasil code that you wrote.  It looks good to me.  :smile:

**Comment by smiths** [comment]
Oh, something else that I noticed is that running `make` produces an error message.  I believe the problem is that stable does not match the build folder.  You can fix this error by copying the contents of build for your example into the corresponding location in stable.  (The purpose of comparing to stable is for regression testing with Drasil.  We want to make sure that when we make changes they don't break an example that was previously working.)
